[tool.poetry]
name = "poetry"
version = "0.1.0"
description = ""
authors = ["ernestboey"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22"
sqlalchemy = "^1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
